openapi: 3.0.3
info:
  title: Dataset Web API (Beta Sprint)
  version: 0.1.0
  description: |
    Documentation for the routes that are currently implemented.
    This beta is read-only. Responses reflect the API's actual shape.

servers:
  - url: https://movie-api-group2-20e70498bde4.herokuapp.com
    description: Production (Heroku)
  - url: https://dataset-webapi-group2-1.onrender.com
    description: Production (Render)
  - url: http://localhost:3000
    description: Local development

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: API key for authentication

security:
  - ApiKeyAuth: []

paths:
  /api/hello:
    get:
      tags: [System]
      summary: Sanity / health check
      security: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello from Group 2 👋

  /api/v1/moviebyyear:
    get:
      tags: [Movies]
      summary: List movies released in a given year
      security:
        - ApiKeyAuth: []
      parameters:
        - in: query
          name: year
          required: true
          schema:
            type: integer
            example: 2023
          description: 4-digit release year to filter by
      responses:
        "200":
          description: Movies for the given year (array may be empty when no matches)
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        movie_id:
                          type: integer
                          example: 13046
                        title:
                          type: string
                          example: "2001 Maniacs"
                        release_year:
                          type: integer
                          example: 2005
                        runtime_minutes:
                          type: integer
                          example: 87
                        rating:
                          type: string
                          example: "7.5"        # API returns string
                        box_office:
                          type: string
                          example: "0.00"       # API returns string
                        director_id:
                          type: integer
                          example: 1
                        country_id:
                          type: integer
                          example: 1
                  total:
                    type: integer
                    example: 298
                    description: Total number of movies returned
        "400":
          description: Bad Request - invalid year parameter
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid year"
                  details:
                    type: string
                    example: "year query parameter must be an integer"
externalDocs:
  description: Live API (Render)
  url: https://dataset-webapi-group2-1.onrender.com
